### ISSUE TITLE
Hamburger menu icon click doesn't trigger

### ISSUE THREAD

**Issue by ransomcarroll** [atechapart/responsive-slide-out#17]
The bind for the hamburger menu button needs to not be conditional on the window width. If you rotate a device or scale your browser window down and the menu icon appears, it's not clickable unless you refresh the page.

**Comment by atechapart** [comment]
good catch, issue resolved.

additional changes made to css for styling the slide out panel scrollbar to stay consistently styled when shrinking window size or rotating device
